// Icons are from the 7 Stroke icon font at http://www.pixedin.com
// See http://www.pixedin.com/license

// albums.svg
export const suitesIcon = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by IcoMoon.io -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="32" height="32" viewBox="0 0 32 32">
<g id="icomoon-ignore">
</g>
<path d="M1.606 7.47v21.325h28.789v-21.325h-28.789zM29.328 27.729h-26.656v-19.192h26.656v19.192z" fill="#000000"></path>
<path d="M3.738 5.338h24.524v1.066h-24.524v-1.066z" fill="#000000"></path>
<path d="M5.871 3.205h20.259v1.066h-20.259v-1.066z" fill="#000000"></path>
</svg>`;

// check.svg
export const passIcon = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by IcoMoon.io -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="32" height="32" viewBox="0 0 32 32">
<g id="icomoon-ignore">
</g>
<path d="M16 2.672c-7.361 0-13.328 5.967-13.328 13.328s5.968 13.328 13.328 13.328c7.361 0 13.328-5.967 13.328-13.328s-5.967-13.328-13.328-13.328zM16 28.262c-6.761 0-12.262-5.501-12.262-12.262s5.5-12.262 12.262-12.262c6.761 0 12.262 5.501 12.262 12.262s-5.5 12.262-12.262 12.262z" fill="#000000"></path>
<path d="M22.667 11.241l-8.559 8.299-2.998-2.998c-0.312-0.312-0.818-0.312-1.131 0s-0.312 0.818 0 1.131l3.555 3.555c0.156 0.156 0.361 0.234 0.565 0.234 0.2 0 0.401-0.075 0.556-0.225l9.124-8.848c0.317-0.308 0.325-0.814 0.018-1.131-0.309-0.318-0.814-0.325-1.131-0.018z" fill="#000000"></path>
</svg>`;

// close-circle.svg
export const failIcon = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by IcoMoon.io -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="32" height="32" viewBox="0 0 32 32">
<g id="icomoon-ignore">
</g>
<path d="M6.576 6.576c-5.205 5.205-5.205 13.643 0 18.849s13.643 5.205 18.849-0c5.206-5.206 5.206-13.643 0-18.849s-13.643-5.205-18.849 0zM24.67 24.67c-4.781 4.781-12.56 4.781-17.341 0s-4.781-12.56 0-17.341c4.781-4.781 12.56-4.781 17.341 0s4.78 12.56-0 17.341z" fill="#000000"></path>
<path d="M10.722 9.969l-0.754 0.754 5.278 5.278-5.253 5.253 0.754 0.754 5.253-5.253 5.253 5.253 0.754-0.754-5.253-5.253 5.278-5.278-0.754-0.754-5.278 5.278z" fill="#000000"></path>
</svg>`;

// gleam.svg
export const testsIcon = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by IcoMoon.io -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="32" height="32" viewBox="0 0 32 32">
<g id="icomoon-ignore">
</g>
<path d="M18.726 3.773l-1.375 11.16h6.088l-10.165 13.293 1.376-11.16h-6.088l10.165-13.293zM20.265 0.006l-13.861 18.126h7.040l-1.709 13.861 13.861-18.126h-7.040l1.709-13.861z" fill="#000000"></path>
</svg>`;

// less.svg
export const skipIcon = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by IcoMoon.io -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="32" height="32" viewBox="0 0 32 32">
<g id="icomoon-ignore">
</g>
<path d="M16 2.672c-7.362 0-13.328 5.966-13.328 13.328s5.966 13.328 13.328 13.328c7.362 0 13.328-5.966 13.328-13.328s-5.966-13.328-13.328-13.328zM16 28.262c-6.761 0-12.262-5.501-12.262-12.262s5.501-12.262 12.262-12.262c6.761 0 12.262 5.501 12.262 12.262s-5.501 12.262-12.262 12.262z" fill="#000000"></path>
<path d="M9.105 15.467h13.826v1.066h-13.826v-1.066z" fill="#000000"></path>
</svg>`;

// stopwatch.svg
export const timeIcon = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by IcoMoon.io -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="32" height="32" viewBox="0 0 32 32">
<g id="icomoon-ignore">
</g>
<path d="M25.039 8.781l0.902-0.902 0.914 0.914 1.131-1.131-2.582-2.582-1.131 1.131 0.914 0.914-0.902 0.902c-1.999-1.833-4.607-3.008-7.485-3.195v-2.161h-1.599v2.161c-6.399 0.412-11.462 5.73-11.462 12.234 0 6.772 5.49 12.262 12.262 12.262s12.262-5.489 12.262-12.262c0-3.195-1.222-6.103-3.223-8.285zM16 28.262c-6.173 0-11.196-5.023-11.196-11.196s5.023-11.196 11.196-11.196 11.196 5.022 11.196 11.196c0 6.173-5.023 11.196-11.196 11.196z" fill="#000000"></path>
<path d="M16.533 15.565v-7.029h-1.066v7.029c-0.62 0.221-1.066 0.806-1.066 1.502s0.447 1.281 1.066 1.502v2.23h1.066v-2.23c0.62-0.221 1.066-0.806 1.066-1.502s-0.447-1.281-1.066-1.502z" fill="#000000"></path>
</svg>`;
