define([
	'./main',
	'./order',
	'./lib/EnvironmentType',
	'./lib/Suite',
	'./lib/Test',
	'./lib/util',
	'./lib/ReporterManager',
	'./lib/interfaces/tdd',
	'./lib/interfaces/bdd',
	'./lib/interfaces/object',
	'./lib/interfaces/qunit',
	'./lib/reporters/Console',
	'dojo-core/has!host-node?./lib/Proxy',
	'dojo-core/has!host-node?./lib/reporters/Pretty',
	'dojo-core/has!host-node?./lib/reporters/TeamCity',
	'dojo-core/has!host-node?./lib/reporters/JUnit',
	'dojo-core/has!host-node?./lib/reporters/Lcov'
], function () {});
